### ISSUE TITLE
is not a issue realy

### ISSUE THREAD

**Issue by luizamboni** [pelias/scripts#10]
is interesting see the context use of scripts : ) , query and indexes useds

**Comment by riordan** [comment]
Thank you! Glad it was interesting.

Was there anything in particular you found useful?

**Comment by luizamboni** [comment]
yes, was useful, i have experience in relational bases, with SQL , then a document base aproach is a challenge, when i had index a relational base in elasticsearch much things that i made using sub-queries to generate derevad tables with evalueted fields is complicate to "translate" to ES....like

SELECT * FROM (SELECT *, CASE WHEN p2.distinct_prices = 1 AND p2.min_price = p2.new_price THEN 'equal' WHEN p2.concurrents_count = 0 THEN 'unique' WHEN p2.new_price <= p2.min_price THEN 'winning' WHEN p2.new_price > p2.min_price THEN 'losing' ELSE 'winning' END AS status, IF( p2.new_price = p2.min_price, p2.new_price/(SELECT min(new_price) FROM products WHERE products.ean = p2.ean AND products.id != p2.id AND products.seller_id != p2.seller_id AND seller_id in (3, 4, 5, 7, 2)) * 100 - 100, p2.new_price/p2.min_price * 100 -100 ) AS diff_percent, p2.new_price - p2.min_price AS diff_price FROM (SELECT *, (SELECT count(*) FROM products WHERE products.ean = p1.ean AND products.seller_id != p1.seller_id AND products.new_price < p1.new_price AND seller_id in (3, 4, 5, 7, 2)) losing_count, (SELECT count(*) FROM products WHERE products.ean = p1.ean AND products.seller_id != p1.seller_id AND seller_id in (3, 4, 5, 7, 2)) concurrents_count, (SELECT min(new_price) FROM products WHERE products.ean = p1.ean AND products.seller_id != p1.seller_id AND seller_id in (3, 4, 5, 7, 2)) min_price, (SELECT max(new_price) FROM products WHERE products.ean = p1.ean AND products.seller_id != p1.seller_id AND seller_id in (3, 4, 5, 7, 2)) max_price, (SELECT count(DISTINCT(new_price)) FROM products WHERE products.ean = p1.ean AND products.seller_id != p1.seller_id AND seller_id in (3, 4, 5, 7, 2)) distinct_prices, ABS(TIMESTAMPDIFF(SECOND,NOW(), p1.crawled_at)) as crawled_at_seconds FROM (SELECT * FROM products WHERE seller_id in (3, 4, 5, 7, 2)) AS p1 ) p2) products  WHERE `products`.`seller_id` = 2 

kkkk..it is true story.
