### ISSUE TITLE
make exact-matches account for hyphens

### ISSUE THREAD

**Issue by sevko** [pelias/scripts#8]
The `exact_match.groovy` script tokenizes the `input` only on spaces, but should account for hyphens as well. Use the `' |-'` delimiter regex instead of just `' '`.

**Comment by dianashk** [comment]
Should account for `,` and possibly others. Here's one that will benefit from that:

`http://pelias.stage.mapzen.com/search?input=eek%20ak`

expecting the following to be at the top

```
{
id: "5861393",
layer: "geoname",
name: "Eek",
alpha3: "USA",
admin0: "United States",
admin1: "Alaska",
admin1_abbr: "AK",
admin2: "Bethel Census Area",
locality: "Eek",
category: [
"admin:city",
"admin"
],
address: { },
text: "Eek, AK"
},
```

**Comment by missinglink** [comment]
hey @dianashk only just seen this now, I think the above is a different issue?

I think the city is called `Eek` (cool name btw) in the state of Alaska (AK)?

sevko was talking about the exact match groovy script (which is now probably being replaced by shingles/phrase matching).

The comma is a special char for input text as it delimits 'parts', if you add a comma to your input text as per http://pelias.stage.mapzen.com/search?input=eek,%20ak then it matches correctly as `a place called 'eek' in the admin area 'ak'`
